version: "3.7"
services:     
    py-cal-bot:
        build:
            context: ./
        environment: 
            BOT_TOKEN: '<TELEGRAME BOT TOKEN>'
            CALENDAR_ID: '<GOOGLE CALENDAR ID>'