version: "3.7"
services:     
    py-cal-bot:
        build:
            context: ./
        env_file: docker.env
        volumes:
            - ./client_secret.json:/usr/src/app/client_secret.json
            - ./token.json:/usr/src/app/token.json
